# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0049_rackreservation_change_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfaceconnection',
            name='connection_name',
            field=models.CharField(blank=True, max_length=69, verbose_name='Connection Name'),
        ),
    ]
